# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/webserver
- name: Installeer Apache en PHP
  ansible.builtin.apt:
    name: "{{ apache_packages }}"
    state: present
  notify: Restart Apache

- name: Start en activeer Apache
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true
